### ISSUE TITLE
advisor report - bullets

### ISSUE THREAD

**Issue by dino-at-thegovlab** [GovLab/sourcerer#10]
Some of the last bullets have the wrong margin.

**Comment by sahuguet** [comment]
Focus on the content. Cosmetics details are for later.

On Mon, Feb 9, 2015 at 12:33 PM, Dinorah Cantú-Pedraza <
notifications@github.com> wrote:

> Some of the last bullets have the wrong margin.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/sourcerer/issues/10.

## 

Arnaud Sahuguet
– Chief Technology Officer

**Comment by dino-at-thegovlab** [comment]
@sahuguet I am focused on the content, but as I'm interacting with the site, cosmetics improvements are important to identify and add to the pending issues to deal with (later than sooner)

**Comment by sahuguet** [comment]
Yes, but since Luis is working on the site, your comments might be
irrelevant by the time you are done with the content.

On Mon, Feb 9, 2015 at 12:43 PM, Dinorah Cantú-Pedraza <
notifications@github.com> wrote:

> @sahuguet https://github.com/sahuguet I am focused on the content, but
> as I'm interacting with the site, cosmetics improvements are important to
> identify and add to the pending issues to deal with (later than sooner)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/sourcerer/issues/10#issuecomment-73553880.

## 

Arnaud Sahuguet
– Chief Technology Officer

**Comment by luisdaniel** [comment]
The site needs to work first. 

I know the site needs cosmetic improvements. It looks like shit right now.

**Comment by dino-at-thegovlab** [comment]
Yes, thanks :smile:
