### ISSUE TITLE
Report Generator

### ISSUE THREAD

**Issue by luisdaniel** [GovLab/sourcerer#14]
FYI, but basically I just need weight for the first three. Everything else is up to you whether you wanna fix.

The following dimensions are missing from the enums.yaml file. I can add, but I need weight.
- Limit Participation to a Defined Community
- Anyone Willing to Participate
- Emails

The following dimensions do not have a corresponding section in the report (does not affect functionality):
- Altruistic Incentive
- Recreational Incentive
- Network Building
- Identity and Portfolio Building
- Personal Satisfaction
- Rating

The following report sections do not correspond to any dimension (does not affect functionality, although it will never appear):
- Prioritizing

**Comment by dino-at-thegovlab** [comment]
For the case-studied proximity algorithm:

Please do not take into consideration the category on limiting participation with the a) "Limit Participation to a Defined Community" or b) "Anyone Willing to Participate variables". 

But yes, thanks for adding the emails variable. 

For the highlights on the report: 

For the category of incentives: 

We are missing to include highlights on recently incorporated variables to the Incentives category. Will work on it next week, if it doesn't affect construction of the site, etc... ("Altruistic Incentive", "Recreational Incentive", "Network Building", "Identity and Portfolio Building", and "Personal Satisfaction")

For the category of quality control: 
-  "rating" and "prioritizing" are the same variable
