### ISSUE TITLE
link to the govlab academy

### ISSUE THREAD

**Issue by dino-at-thegovlab** [GovLab/sourcerer#16]
Was thinking that after the report, it would be a good idea to add the following:

Passionate about the uses of Crowdsourcing in the Public Sector? Visit (The GovLab Academy)[http://govlabacademy.org/] for additional content to help you get started in your own crowdsourcing project or contact us to crowdsourcing@thegovlab.org, we are happy to help!

@sahuguet could you create that account?

**Comment by sahuguet** [comment]
We can do that.
We can also have a info@thegovlab where we make the subject be
crowdsourcing.

On Sun, Feb 15, 2015 at 4:22 PM, Dinorah Cantú-Pedraza <
notifications@github.com> wrote:

> Was thinking that after the report, it would be a good idea to add the
> following:
> 
> Passionate about the uses of Crowdsourcing in the Public Sector? Visit
> (The GovLab Academy)[http://govlabacademy.org/] for additional content to
> help you get started in your own crowdsourcing project or contact us to
> crowdsourcing@thegovlab.org, we are happy to help!
> 
> @sahuguet https://github.com/sahuguet could you create that account?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/sourcerer/issues/16.

## 

Arnaud Sahuguet
– Chief Technology Officer

**Comment by dino-at-thegovlab** [comment]
Thanks :-) 

Does the info account gets lots of emails? 

I'm thinking about also creating a mailing list, to send monthly updates or something like that who people who subscribes so, maybe new account only for crowdsourcing is better to also add it as the reference on mailchimp, etc.

**Comment by luisdaniel** [comment]
> Passionate about the uses of Crowdsourcing in the Public Sector? Visit (The GovLab Academy)[http://govlabacademy.org/] for additional content to help you get started in your own crowdsourcing project or contact us to crowdsourcing@thegovlab.org, we are happy to help!

Is that the final text you want to have?

**Comment by dino-at-thegovlab** [comment]
At the end of the report, yes.

**Comment by luisdaniel** [comment]
done.
