### ISSUE TITLE
Making the first case-study a button that sends to the questionnaire 

### ISSUE THREAD

**Issue by dino-at-thegovlab** [GovLab/sourcerer#20]
It can read "add your crowdsourcing story"

**Comment by luisdaniel** [comment]
A lot of what we've been doing is patching and hacking the original template to suit our needs.  The case studies tile section works a certain way: You click a + button and you get a "pop up" html. For now, I can't figure out an easy way to prevent the tiles library from trying to open a pop up instead of just linking somewhere else. 

The other option is make the form into a "Project" and have a special page for that. But it'll work the same way as other projects: you'll get a pop-up. 

I'll leave this as low priority since there is a bunch of hacking together involved.

**Comment by dino-at-thegovlab** [comment]
Okok, will work on it as a case study, but, can you make it be always the first one?

**Comment by luisdaniel** [comment]
no no, the problem is that I can't make it link to some other page. As crazy as it sounds. 
If I click on a case study I get a pop-up, not a new page like a regular link.

**Comment by dino-at-thegovlab** [comment]
Yes, I will create it as a case-study, and give a brief explanation of the questionnaire, and then add the link :) but can you make it always be the one on the top left corner?

**Comment by luisdaniel** [comment]
hmm..... bueno

Case studies are oredered alphanumerically, so just title it "000" and hope that someone doesn't call their project "00".

**Comment by dino-at-thegovlab** [comment]
Here an example of how thetoolbox.org does this feature:

![screen shot 2015-03-10 at 1 35 58 am 2](https://cloud.githubusercontent.com/assets/8558994/6569739/fa847020-c6c5-11e4-909c-85d782c36fbd.png)

**Comment by sahuguet** [comment]
There is an easier way.
In the HTML, we had a first item by hand and then we loop over the case
studies.
For the first item, we can change everything we want.

This is the current stuff.
We just need to remove all the stuff we don't want and instead add a link
that points to the form.

<li class="cbp-item case-studies national nonprofit tasks 1200usdyear "> <div
class="cbp-caption"> <div class="cbp-caption-defaultWrap"> <img src="
img/casestudies/adopt-a-hydrant-small.png
<http://sourcerer.s3-website-us-east-1.amazonaws.com/img/casestudies/adopt-a-hydrant-small.png>"
alt="" width="100%"> </div> <div class="cbp-caption-activeWrap"> <div class
="cbp-l-caption-alignCenter"> <div class="cbp-l-caption-body"> <a href="
ajax/adopt-a-hydrant.html
<http://sourcerer.s3-website-us-east-1.amazonaws.com/ajax/adopt-a-hydrant.html>"
class="cbp-singlePage cbp-l-caption-buttonLeft"><i class="pe-3x pe-7s-plus">
</i></a> <a href="img/casestudies/adopt-a-hydrant-big.png
<http://sourcerer.s3-website-us-east-1.amazonaws.com/img/casestudies/adopt-a-hydrant-big.png>"
class="cbp-lightbox cbp-l-caption-buttonRight" data-title=""><i class="pe-3x
pe-7s-search"></i></a> </div> </div> </div> </div> <div class="
cbp-l-grid-projects-title">Adopt-a-Hydrant</div> <div class="
cbp-l-grid-projects-desc">Civic participation, Environment and weather,
Geospatial mapping</div> </li>

On Tue, Mar 10, 2015 at 1:37 AM, Dinorah Cantú-Pedraza <
notifications@github.com> wrote:

> Here an example of how thetoolbox.org does this feature:
> 
> [image: screen shot 2015-03-10 at 1 35 58 am 2]
> https://cloud.githubusercontent.com/assets/8558994/6569739/fa847020-c6c5-11e4-909c-85d782c36fbd.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/sourcerer/issues/20#issuecomment-77998673.

## 

Arnaud Sahuguet
– Chief Technology Officer

**Comment by luisdaniel** [comment]
I'll show you guys the issue tomorrow. Go to sleep.

**Comment by luisdaniel** [comment]
done
