### ISSUE TITLE
Creating tiles for academic papers, displayed like the case-studies are

### ISSUE THREAD

**Issue by dino-at-thegovlab** [GovLab/sourcerer#22]
Content to be displayed when clicked on the entry:
- Author(s)
- Summary
- Highlights (3 - 5 bullets)
- Learnings (3 - 5 bullets)
- Link to the paper

**Comment by luisdaniel** [comment]
I need one or two examples/entries to work with. 

Use the case_studies.yaml file and follow the exact format as case studies. Except under `type:` write in "Research Papers"
