### ISSUE TITLE
buying domain and adding the site to the domain 

### ISSUE THREAD

**Issue by dino-at-thegovlab** [GovLab/sourcerer#23]
We are going to use all of this:

crowdsorcerer.org
crowdsourcingadvisor.org 
thecrowdsourcingadvisor.org
crowdsourcingadvisor.com 
thecrowdsourcingadvisor.com

**Comment by sahuguet** [comment]
I could get 4 out of 5.

Product
Quantity
Term
Price
.COM Domain Registration
thecrowdsourcingadvisor.com
https://dcc.godaddy.com/default.aspx?activeview=domains&isc=gdbbp1901&ci=95165&cvosrc=bounceback.1901.gdbbp1901
1 Domain
1 Year
$13.17
.ORG Domain Registration
thecrowdsourcingadvisor.org
https://dcc.godaddy.com/default.aspx?activeview=domains&isc=gdbbp1901&ci=95165&cvosrc=bounceback.1901.gdbbp1901
1 Domain
1 Year
$9.17
.ORG Domain Registration
crowdsourcingadvisor.org
https://dcc.godaddy.com/default.aspx?activeview=domains&isc=gdbbp1901&ci=95165&cvosrc=bounceback.1901.gdbbp1901
1 Domain
1 Year
$9.17
.ORG Domain Registration
crowdsorcerer.org
https://dcc.godaddy.com/default.aspx?activeview=domains&isc=gdbbp1901&ci=95165&cvosrc=bounceback.1901.gdbbp1901
1 Domain
1 Year
$9.17
Subtotal:
$40.68
Tax:
$0.00
Total:
$40.68

On Wed, Mar 4, 2015 at 2:37 PM, Dinorah Cantú-Pedraza <
notifications@github.com> wrote:

> We are going to use all of this:
> 
> crowdsorcerer.org
> crowdsourcingadvisor.org
> thecrowdsourcingadvisor.org
> crowdsourcingadvisor.com
> thecrowdsourcingadvisor.com
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/sourcerer/issues/23.

## 

Arnaud Sahuguet
– Chief Technology Officer

**Comment by dino-at-thegovlab** [comment]
Kewl. 

Can we move the site there?

**Comment by sahuguet** [comment]
When the bugs are fixed, sure.

On Wed, Mar 4, 2015 at 3:44 PM, Dinorah Cantú-Pedraza <
notifications@github.com> wrote:

> Kewl.
> 
> Can we move the site there?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/sourcerer/issues/23#issuecomment-77243209.

## 

Arnaud Sahuguet
– Chief Technology Officer
