### ISSUE TITLE
Adding Discourse to the site

### ISSUE THREAD

**Issue by dino-at-thegovlab** [GovLab/sourcerer#24]
discuss.crowdsorcerer.org and also adding it as a tab in the site called "community"

**Comment by sahuguet** [comment]
We are not creating a discourse for each project.
Let's have a category on Civic Discourse for Crowdsourcing and point people
there.

On Thu, Mar 5, 2015 at 4:06 PM, Luis notifications@github.com wrote:

> Assigned #24 https://github.com/GovLab/sourcerer/issues/24 to @sahuguet
> https://github.com/sahuguet.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/sourcerer/issues/24#event-247090444.

## 

Arnaud Sahuguet
– Chief Technology Officer

**Comment by dino-at-thegovlab** [comment]
oh god... hahahaha you change your mind every week! 

I'm cool with that. I wanted to have civic discourse for all, but you made me have an academy one... 

@luisdaniel could you add a tab and direct to the specific category on civic discourse? And can I please be an admin of civic discourse too? to be able to create the category, etc...

**Comment by sahuguet** [comment]
No I don't.
Academy is special. Dedicated site.
Crowdsourcing people are regular civic minded people. They can use the
regular site.

**Comment by luisdaniel** [comment]
done.

**Comment by dino-at-thegovlab** [comment]
Correct link: http://www.civic-discourse.org/c/crowdsorcerer-community
- switch place with the about tab (first about, then community)

**Comment by luisdaniel** [comment]
fixed
