### ISSUE TITLE
Feature to download case-studies 

### ISSUE THREAD

**Issue by dino-at-thegovlab** [GovLab/sourcerer#25]

**Comment by luisdaniel** [comment]
working on this one. Will go in order, so I won't look at the other issues for now.
Have to fix the entire YAML file. Might take hours.

**Comment by dino-at-thegovlab** [comment]
Ok! Will work on the contribute content and icon. 

Tomorrow we can discuss this, because it is important that we do things right so no one looses time doing this.

**Comment by luisdaniel** [comment]
done
