### ISSUE TITLE
map visualization

### ISSUE THREAD

**Issue by dino-at-thegovlab** [GovLab/sourcerer#28]
Add it as a tab that reads: map

Same way it works for OD500MX: http://www.opendata500.com/mx/list/

Only using filter by activity.  

BTW.... site offers the option to download CVS (all and by some filters)... thought you said we could specify what to download?

**Comment by luisdaniel** [comment]
These are your locations: 
['British Columbia', 'Pennsylvania', 'CA', 'DC', 'NY', 'Massachusetts', u'Nuevo Le\xf3n', None]
7 places in 3 different countries. I think it's too early for a map.

**Comment by dino-at-thegovlab** [comment]
I'm scared that you leave and the next person is not good at it. Can we have it and not enabled for people to see it?

**Comment by luisdaniel** [comment]
I'll leave this last, since at the pace I'm moving through all the issues, I don;t know if I'll be able to finish them all.
