### ISSUE TITLE
advisor content

### ISSUE THREAD

**Issue by dino-at-thegovlab** [GovLab/sourcerer#3]
Hey, we need the content of the advisor (questions, answers and report) to be on a place where we can constantly edit it. 

The idea is for us to continuously get smarter = continuously improve the highlights.

**Comment by luisdaniel** [comment]
Doable. Let me fix some other stuff first.

**Comment by sahuguet** [comment]
Let's launch with what we have first and then we can think about future
versions of the tool.

On Mon, Feb 9, 2015 at 2:09 PM, Luis notifications@github.com wrote:

> Doable. Let me fix some other stuff first.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/sourcerer/issues/3#issuecomment-73569458.

## 

Arnaud Sahuguet
– Chief Technology Officer
