### ISSUE TITLE
logo of the site

### ISSUE THREAD

**Issue by dino-at-thegovlab** [GovLab/sourcerer#32]
Change to:
The Crowdsorcerer: The Governance Lab's Crowdsourcing Design Advisor

Beth says:
The logo has to embody the idea of doing magic
My opinion:
The logo should have the square made out of points

@luisdaniel you are the expert so could you make some options and variants under these guidelines

**Comment by luisdaniel** [comment]
That title is way too long. It takes four lines to display that title.

My "expert" opinion:
Title is max two words.
The logo is just the title with a nice font (which you can change if you want). No icon. Icon is cheesy and tacky.

**Comment by dino-at-thegovlab** [comment]
If we want to have the name "crowdsorcerer" then we have to add the other stuff... at least for the beginning. 

Having the word has been a hard negotiation so let's start with the long title and then, when they realize the word sticks and people really like it, we can delete the rest. To avoid the 4 paragraphs, change the full name for just The GovLab. 

Let's see how that looks. Icons are good for brand purposes. Specially with a long name, we need an icon to just display it and the name crowdsorcerer. But I'm against the magic icon... the word is enough. For the square one because is the best icon I've seen that describes crowdsourcing. Not just connecting dots but also no top-down but more "equilateral" structure for governance.

**Comment by luisdaniel** [comment]
It looks horrible.
