### ISSUE TITLE
PDF report does not display tiles properly

### ISSUE THREAD

**Issue by sahuguet** [GovLab/sourcerer#34]
See email PDF from Sam + my email.

**Comment by dino-at-thegovlab** [comment]
![screen shot 2015-03-04 at 4 10 01 pm 2](https://cloud.githubusercontent.com/assets/8558994/6493493/00b3853a-c289-11e4-8566-632f81d61da0.png)

**Comment by dino-at-thegovlab** [comment]
There :)

**Comment by luisdaniel** [comment]
done. case studies are hidden.
