### ISSUE TITLE
include inside the first "try the advisor" button

### ISSUE THREAD

**Issue by dino-at-thegovlab** [GovLab/sourcerer#42]
The: "Find out how & when to use crowdsourcing!" high pitch. 

And therefore, make the button bigger. 

Beth's request.

**Comment by luisdaniel** [comment]
I don't like how it looks: 

![screen shot 2015-03-06 at 4 28 39 pm](https://cloud.githubusercontent.com/assets/1385030/6536711/f0c700fc-c41d-11e4-945e-823340c20646.png)
