### ISSUE TITLE
report as a PDF

### ISSUE THREAD

**Issue by dino-at-thegovlab** [GovLab/sourcerer#5]
Can the report also be downloaded as a PDF?

**Comment by sahuguet** [comment]
no.
But people can print and save as PDF.
Easier and better.

On Fri, Feb 6, 2015 at 12:03 PM, Dinorah Cantú-Pedraza <
notifications@github.com> wrote:

> Can the report also be downloaded as a PDF?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/sourcerer/issues/5.

## 

Arnaud Sahuguet
– Chief Technology Officer

**Comment by dino-at-thegovlab** [comment]
Not sure that it is better... but ok.

**Comment by luisdaniel** [comment]
If they can't Print > Save As PDF, then they shouldn't be allowed to use a computer. 

I'll work on making the report printer-(and hence PDF)-friendly

**Comment by luisdaniel** [comment]
printable.
