### ISSUE TITLE
Advisor - Landing page - content change

### ISSUE THREAD

**Issue by dino-at-thegovlab** [GovLab/sourcerer#7]
Content change: 

The Crowdsourcing Advisor will briefly interview you and based on your answers it will offer you a detailed report, including general comments and existing cases that used crowdsourcing in a similar manner to your particular situation.

Everything else, delete. 

Are we going to be able to edit the content directly? as suggested in a previous issue.

**Comment by luisdaniel** [comment]
since we're going to have multiple languages apparently, I'll eventually put all text on a YAML file that you'll have to translate. All text will then be pulled from that yaml file. This will be done at the end though.

**Comment by dino-at-thegovlab** [comment]
The Crowdsourcing Advisor will briefly interview you and based on your answers it will:
- Help you find out if crowdsourcing is the right fit for their project;
- Help you identify objectives, intended audience, tasks to be undertaken and the basic elements about crowdsourcing that need take into consideration;
- Produce you a tailored report that includes the relevant highlights to your particular circumstance; and
- Present you the top 3 relevant case studies most similar to your needs and circumstances.

**Comment by luisdaniel** [comment]
I will remove the quote (otherwise it's too much text) and add these bullets. 

All text changes for the advisor are now closed for a week. Formatting each section of the text is a huge hassle.
