### ISSUE TITLE
advisor - landing page - pop ups are missing

### ISSUE THREAD

**Issue by dino-at-thegovlab** [GovLab/sourcerer#8]
why? 

pop-ups missing:
- What is crowdsourcing?
- More about this advisor

**Comment by luisdaniel** [comment]
why? 

pues por que no lo he hecho.

**Comment by dino-at-thegovlab** [comment]
jajajaja ok ok, solamente quería saber si por algo no se podían incluir

**Comment by luisdaniel** [comment]
No pop-ups. Just displaying them. 

Check to see if like.
