### ISSUE TITLE
case studies - matching system 

### ISSUE THREAD

**Issue by dino-at-thegovlab** [GovLab/sourcerer#9]
Hey @sahuguet how does this word? 

There are some variables that we need to add + we need a place for us to constantly upload and tag the case-studies.

**Comment by sahuguet** [comment]
Ask Luis. He has a good suggestion for it.

On Mon, Feb 9, 2015 at 12:30 PM, Dinorah Cantú-Pedraza <
notifications@github.com> wrote:

> Hey @sahuguet https://github.com/sahuguet how does this word?
> 
> There are some variables that we need to add + we need a place for us to
> constantly upload and tag the case-studies.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/sourcerer/issues/9.

## 

Arnaud Sahuguet
– Chief Technology Officer

**Comment by dino-at-thegovlab** [comment]
Ok

**Comment by luisdaniel** [comment]
We have to have a list of set variables. This can be on the enums.yaml file. 

If you put a variable on the case study that is not on the list of approved variables, it won't work.

We need to meet and discuss what are these variables called: there's 'focus', 'activity', 'incentives', etc and I dunno what goes where.

This is the first thing that needs to be done before I can continue doing anything else.
